### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by kachkaev** [effrenus/yandex-map-react#1]
Hi Alexey! Thanks for your efforts to create the yandex maps component! If this is something production-ready, could you please add a short description of the features in README.md? 

I've been trying to find such a component recently but with no results so far. Ended up creating [a discussion in the yandex maps club](https://yandex.ru/blog/mapsapi/yandex-maps-react).

**Comment by effrenus** [comment]
Hi. Actually component now in beta stage, so breaking changes is possible in future release.
Also component needs tests. README and example add today.
