### ISSUE TITLE
proposal: add options and properties props handling to MapMarker component

### ISSUE THREAD

**Issue by gribnoysup** [effrenus/yandex-map-react#19]
I really needed properties and options support for MapMarker so I added it.

I created a PR #18 with added support for Placemark [options](https://tech.yandex.ru/maps/doc/jsapi/2.0/ref/reference/GeoObject-docpage/#param-options) and [properties](https://tech.yandex.ru/maps/doc/jsapi/2.0/ref/reference/GeoObject-docpage/#param-feature.properties). Not sure that this is the best possible implementation, so maybe any comments/ideas?

**Comment by effrenus** [comment]
Looks good, thanks.

**Comment by gribnoysup** [comment]
np :) great module btw!
