### ISSUE TITLE
Cannot update center through props

### ISSUE THREAD

**Issue by ghost** [effrenus/yandex-map-react#22]
It seems to be impossible to update center through props.

I've looked into the code, nextProps will be ignored except `controls`, does it mean that you cannot change either initialCenter or initialZoom with props, but manage it through the map instance, with maps methods outside the `<Map />`?

**Comment by ghost** [comment]
https://github.com/effrenus/yandex-map-react/pull/23

**Comment by effrenus** [comment]
Seems you are right) Thanks for PR
