### ISSUE TITLE
Доступ к ymaps.geocode() или прямой доступ к API

### ISSUE THREAD

**Issue by ts-ign0re** [effrenus/yandex-map-react#31]
Всем привет, простите что по русски. Есть ли возможность в текущей версии использовать ymaps.geocode()? Можно задать вопрос по другому, есть ли способ получить доступ к ./api напрямую, например 

```
import {Map, Marker, API} from 'yandex-map-react';
```

Спасибо

**Comment by effrenus** [comment]
Привет. `window.ymaps`? В текущей версии такой возможности нет. Посмотрел твой форк, для ображения к АПИ надо сделать `api.getAPI()` (это не красиво, согласен):
См. для примера https://github.com/effrenus/yandex-map-react/blob/master/src/controllers/MarkerController.js

**Comment by ts-ign0re** [comment]
окей, спасибо, с этим я уже разобрался, думал если есть желание мог бы вынести апи в exports, сделав зависимость явной и отправить pr

**Comment by effrenus** [comment]
Есть еще такой вариант `import ymapAPI from 'yandex-map-react/lib/api';` Пока не хочется выносить в дефолтный экспорт.
