### ISSUE TITLE
Set lang parameter

### ISSUE THREAD

**Issue by onufrienko** [effrenus/yandex-map-react#41]
Hi :)
I need set lang=en_US. How can I do it?

**Comment by effrenus** [comment]
You can use `loadOptions` (more details in readme): `<Map loadOptions={{lang: 'es_US'}} />`. Thanks @MikeDevice

**Comment by onufrienko** [comment]
Thank!

P.S. how can I disable zooming the map with the mouse wheel? 
(https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/behavior.ScrollZoom-docpage/)

**Comment by MikeDevice** [comment]
You can use [behaviors](https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/Map-docpage/#param-state.behaviors) option
```jsx
var behaviors: ['drag', 'multiTouch'];
<Map state={{controls: [], behaviors}}>
```
