### ISSUE TITLE
Update to react v15.0

### ISSUE THREAD

**Issue by kachkaev** [effrenus/yandex-map-react#8]
After upgrading to react@15.0.2 npm starts complaining:

```
npm WARN yandex-map-react@1.0.0-beta.4 requires a peer of react@^0.14.8 but none was installed.
```

Patch example: https://github.com/STRML/react-grid-layout/commit/ef335bcc11652df0ff7cd649d9bc265acf339faf
(not submitting a PR since I don't know whether it is just about changing a version or there should be some modifications in the code too)

**Comment by effrenus** [comment]
Update dependencies. Watched [changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md), don't expect any problems.
